/*
 *
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef R_ERROR_ID_H
#define R_ERROR_ID_H

/**
 * @defgroup Error_Domain_ID Error Domain ID
 * @{
 * @brief This module provides typedef of Error Domain ID.
 *
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief X5H Error Domain ID.
 */
typedef enum {
    DBSC5_DSBS0_DFI_DOMAIN_NORMAL_ECM_ERROR = 0,
    DBSC5_DSBS0_AXI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS1_DFI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS1_AXI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS2_DFI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS2_AXI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS3_DFI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS3_AXI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS4_DFI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS4_AXI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS5_DFI_DOMAIN_NORMAL_ECM_ERROR,
    DBSC5_DSBS5_AXI_DOMAIN_NORMAL_ECM_ERROR,
    INTERNAL_BUS_FUSA_ERROR = 29,
    WWDT10_DETECTS_ERROR_RES_IS_OUTPUT = 44,
    WWDT11_DETECTS_ERROR_RES_IS_OUTPUT = 45,
    WWDT12_DETECTS_ERROR_RES_IS_OUTPUT = 46,
    WWDT13_DETECTS_ERROR_RES_IS_OUTPUT = 47,
    WWDT9_DETECTS_ERROR_RES_IS_OUTPUT = 48,
    WWDT8_DETECTS_ERROR_RES_IS_OUTPUT = 49,
    WWDT7_DETECTS_ERROR_RES_IS_OUTPUT = 50,
    WWDT6_DETECTS_ERROR_RES_IS_OUTPUT = 51,
    WWDT5_DETECTS_ERROR_RES_IS_OUTPUT = 52,
    WWDT4_DETECTS_ERROR_RES_IS_OUTPUT = 53,
    WWDT3_DETECTS_ERROR_RES_IS_OUTPUT = 54,
    WWDT2_DETECTS_ERROR_RES_IS_OUTPUT = 55,
    WWDT1_DETECTS_ERROR_RES_IS_OUTPUT = 56,
    WWDT0_DETECTS_ERROR_RES_IS_OUTPUT = 57,
    WWDT0_DETECTS_ERROR_NMI_IS_OUTPUT = 200,
    WWDT1_DETECTS_ERROR_NMI_IS_OUTPUT = 201,
    WWDT10_DETECTS_ERROR_NMI_IS_OUTPUT = 202,
    WWDT11_DETECTS_ERROR_NMI_IS_OUTPUT = 203,
    WWDT12_DETECTS_ERROR_NMI_IS_OUTPUT = 226,
    WWDT13_DETECTS_ERROR_NMI_IS_OUTPUT = 227,
    WWDT2_DETECTS_ERROR_NMI_IS_OUTPUT = 228,
    WWDT3_DETECTS_ERROR_NMI_IS_OUTPUT = 229,
    WWDT4_DETECTS_ERROR_NMI_IS_OUTPUT = 230,
    WWDT5_DETECTS_ERROR_NMI_IS_OUTPUT = 231,
    WWDT6_DETECTS_ERROR_NMI_IS_OUTPUT = 232,
    WWDT7_DETECTS_ERROR_NMI_IS_OUTPUT = 233,
    WWDT8_DETECTS_ERROR_NMI_IS_OUTPUT = 234,
    WWDT9_DETECTS_ERROR_NMI_IS_OUTPUT = 235,
    WWDT14_DETECTS_ERROR_NMI_IS_OUTPUT = 720,
    WWDT15_DETECTS_ERROR_NMI_IS_OUTPUT = 721,
    WWDT16_DETECTS_ERROR_NMI_IS_OUTPUT = 722,
    WWDT17_DETECTS_ERROR_NMI_IS_OUTPUT = 723,
    WWDT18_DETECTS_ERROR_NMI_IS_OUTPUT = 724,
    WWDT19_DETECTS_ERROR_NMI_IS_OUTPUT = 725,
    WWDT20_DETECTS_ERROR_NMI_IS_OUTPUT = 726,
    WWDT14_DETECTS_ERROR_RES_IS_OUTPUT = 727,
    WWDT15_DETECTS_ERROR_RES_IS_OUTPUT = 728,
    WWDT16_DETECTS_ERROR_RES_IS_OUTPUT = 729,
    WWDT17_DETECTS_ERROR_RES_IS_OUTPUT = 730,
    WWDT18_DETECTS_ERROR_RES_IS_OUTPUT = 731,
    WWDT19_DETECTS_ERROR_RES_IS_OUTPUT = 732,
    WWDT20_DETECTS_ERROR_RES_IS_OUTPUT = 733,
} e_ecm_error_id_t;

#ifdef __cplusplus
}
#endif

/** @} */ // end

#endif /* R_ERROR_ID_H */