/*
* Copyright (c) 2025 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/*******************************************************************************************************************//**
 * @ingroup BSP_MCU_RH850U2C8
 * @defgroup BSP_DMAC_U2C8 BSP DMAC
 * @brief This module provides the macros, data types, and definition constants required for DMAC.
 *
 * @{
 **********************************************************************************************************************/

#ifndef BSP_DMAC_H
#define BSP_DMAC_H

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/** DMA Trigger Factor */
typedef enum e_dmac_trigger_event
{
    DMAC_TRIGGER_EVENT_PORT_IRQ0               = (0),     ///< IRQ0
    DMAC_TRIGGER_EVENT_PORT_IRQ1               = (1),     ///< IRQ1
    DMAC_TRIGGER_EVENT_PORT_IRQ2               = (2),     ///< IRQ2
    DMAC_TRIGGER_EVENT_PORT_IRQ3               = (3),     ///< IRQ3
    DMAC_TRIGGER_EVENT_PORT_IRQ4               = (4),     ///< IRQ4
    DMAC_TRIGGER_EVENT_PORT_IRQ5               = (5),     ///< IRQ5
    DMAC_TRIGGER_EVENT_PORT_IRQ6               = (6),     ///< IRQ6
    DMAC_TRIGGER_EVENT_PORT_IRQ7               = (7),     ///< IRQ7
    DMAC_TRIGGER_EVENT_PORT_IRQ8               = (8),     ///< IRQ8
    DMAC_TRIGGER_EVENT_PORT_IRQ9               = (9),     ///< IRQ9
    DMAC_TRIGGER_EVENT_PORT_IRQ10              = (10),    ///< IRQ10
    DMAC_TRIGGER_EVENT_PORT_IRQ11              = (11),    ///< IRQ11
    DMAC_TRIGGER_EVENT_PORT_IRQ12              = (12),    ///< IRQ12
    DMAC_TRIGGER_EVENT_PORT_IRQ13              = (13),    ///< IRQ13
    DMAC_TRIGGER_EVENT_PORT_IRQ16              = (16),    ///< IRQ16
    DMAC_TRIGGER_EVENT_PORT_IRQ17              = (17),    ///< IRQ17
    DMAC_TRIGGER_EVENT_PORT_IRQ20              = (20),    ///< IRQ20
    DMAC_TRIGGER_EVENT_PORT_IRQ21              = (21),    ///< IRQ21
    DMAC_TRIGGER_EVENT_PORT_IRQ22              = (22),    ///< IRQ22
    DMAC_TRIGGER_EVENT_PORT_IRQ23              = (23),    ///< IRQ23
    DMAC_TRIGGER_EVENT_PORT_IRQ24              = (24),    ///< IRQ24
    DMAC_TRIGGER_EVENT_PORT_IRQ25              = (25),    ///< IRQ25
    DMAC_TRIGGER_EVENT_PORT_IRQ26              = (26),    ///< IRQ26
    DMAC_TRIGGER_EVENT_PORT_IRQ27              = (27),    ///< IRQ27
    DMAC_TRIGGER_EVENT_PORT_IRQ28              = (28),    ///< IRQ28
    DMAC_TRIGGER_EVENT_PORT_IRQ29              = (29),    ///< IRQ29
    DMAC_TRIGGER_EVENT_PORT_IRQ30              = (30),    ///< IRQ30
    DMAC_TRIGGER_EVENT_PORT_IRQ31              = (31),    ///< IRQ31
    DMAC_TRIGGER_EVENT_PORT_INTTAPA0ESO        = (32),    ///< INTTAPA0ESO
    DMAC_TRIGGER_EVENT_PORT_INTTAPA1ESO        = (33),    ///< INTTAPA1ESO
    DMAC_TRIGGER_EVENT_ADCK_INTADCK1I0         = (34),    ///< INTADCK1I0
    DMAC_TRIGGER_EVENT_ADCK_INTADCK1I1         = (35),    ///< INTADCK1I1
    DMAC_TRIGGER_EVENT_ADCK_INTADCK1I2         = (36),    ///< INTADCK1I2
    DMAC_TRIGGER_EVENT_ADCK_INTADCK1I3         = (37),    ///< INTADCK1I3
    DMAC_TRIGGER_EVENT_ADCK_INTADCK1I4         = (38),    ///< INTADCK1I4
    DMAC_TRIGGER_EVENT_ADCK_ADMPXI1            = (39),    ///< ADMPXI1
    DMAC_TRIGGER_EVENT_ADCK_ADC_CONV_END1      = (40),    ///< ADC_CONV_END1
    DMAC_TRIGGER_EVENT_ADCK_INTADCK_SD1        = (41),    ///< INTADCK_SD1
    DMAC_TRIGGER_EVENT_ADCK_INTADCKAI0         = (42),    ///< INTADCKAI0
    DMAC_TRIGGER_EVENT_ADCK_INTADCKAI1         = (43),    ///< INTADCKAI1
    DMAC_TRIGGER_EVENT_ADCK_INTADCKAI2         = (44),    ///< INTADCKAI2
    DMAC_TRIGGER_EVENT_ADCK_INTADCKAI3         = (45),    ///< INTADCKAI3
    DMAC_TRIGGER_EVENT_ADCK_INTADCKAI4         = (46),    ///< INTADCKAI4
    DMAC_TRIGGER_EVENT_ADCK_ADMPXIA            = (47),    ///< ADMPXIA
    DMAC_TRIGGER_EVENT_ADCK_ADC_CONV_ENDA      = (48),    ///< ADC_CONV_ENDA
    DMAC_TRIGGER_EVENT_ADCK_INTADCK_SDA        = (49),    ///< INTADCK_SDA
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT0RI       = (50),    ///< INTRSENT0RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT1RI       = (51),    ///< INTRSENT1RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT2RI       = (52),    ///< INTRSENT2RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT3RI       = (53),    ///< INTRSENT3RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT4RI       = (54),    ///< INTRSENT4RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT5RI       = (55),    ///< INTRSENT5RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT6RI       = (56),    ///< INTRSENT6RI
    DMAC_TRIGGER_EVENT_RSENT_INTRSENT7RI       = (57),    ///< INTRSENT7RI
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ0  = (58),    ///< INTRCANCFDREQ0
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ1  = (59),    ///< INTRCANCFDREQ1
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ2  = (60),    ///< INTRCANCFDREQ2
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ3  = (61),    ///< INTRCANCFDREQ3
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ4  = (62),    ///< INTRCANCFDREQ4
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ5  = (63),    ///< INTRCANCFDREQ5
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ0  = (64),    ///< INTRCANRFDREQ0
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ1  = (65),    ///< INTRCANRFDREQ1
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ2  = (66),    ///< INTRCANRFDREQ2
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ3  = (67),    ///< INTRCANRFDREQ3
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ4  = (68),    ///< INTRCANRFDREQ4
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ5  = (69),    ///< INTRCANRFDREQ5
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ6  = (70),    ///< INTRCANRFDREQ6
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ7  = (71),    ///< INTRCANRFDREQ7
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN30UR0      = (72),    ///< INTRLIN30UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN30UR1      = (73),    ///< INTRLIN30UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN31UR0      = (74),    ///< INTRLIN31UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN31UR1      = (75),    ///< INTRLIN31UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN32UR0      = (76),    ///< INTRLIN32UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN32UR1      = (77),    ///< INTRLIN32UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN33UR0      = (78),    ///< INTRLIN33UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN33UR1      = (79),    ///< INTRLIN33UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN34UR0      = (80),    ///< INTRLIN34UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN34UR1      = (81),    ///< INTRLIN34UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN35UR0      = (82),    ///< INTRLIN35UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN35UR1      = (83),    ///< INTRLIN35UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN36UR0      = (84),    ///< INTRLIN36UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN36UR1      = (85),    ///< INTRLIN36UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN37UR0      = (86),    ///< INTRLIN37UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN37UR1      = (87),    ///< INTRLIN37UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN38UR0      = (88),    ///< INTRLIN38UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN38UR1      = (89),    ///< INTRLIN38UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN39UR0      = (90),    ///< INTRLIN39UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN39UR1      = (91),    ///< INTRLIN39UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN310UR0     = (92),    ///< INTRLIN310UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN310UR1     = (93),    ///< INTRLIN310UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN311UR0     = (94),    ///< INTRLIN311UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN311UR1     = (95),    ///< INTRLIN311UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN312UR0     = (96),    ///< INTRLIN312UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN312UR1     = (97),    ///< INTRLIN312UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN313UR0     = (98),    ///< INTRLIN313UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN313UR1     = (99),    ///< INTRLIN313UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN314UR0     = (100),   ///< INTRLIN314UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN314UR1     = (101),   ///< INTRLIN314UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN323UR0     = (102),   ///< INTRLIN323UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN323UR1     = (103),   ///< INTRLIN323UR1
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI0           = (104),   ///< DMAMSPI0
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI1           = (105),   ///< DMAMSPI1
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI2           = (106),   ///< DMAMSPI2
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI3           = (107),   ///< DMAMSPI3
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI4           = (108),   ///< DMAMSPI4
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI5           = (109),   ///< DMAMSPI5
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI6           = (110),   ///< DMAMSPI6
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI7           = (111),   ///< DMAMSPI7
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI8           = (112),   ///< DMAMSPI8
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI9           = (113),   ///< DMAMSPI9
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI10          = (114),   ///< DMAMSPI10
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI11          = (115),   ///< DMAMSPI11
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI12          = (116),   ///< DMAMSPI12
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI13          = (117),   ///< DMAMSPI13
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI14          = (118),   ///< DMAMSPI14
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI15          = (119),   ///< DMAMSPI15
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI16          = (120),   ///< DMAMSPI16
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI17          = (121),   ///< DMAMSPI17
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI18          = (122),   ///< DMAMSPI18
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI19          = (123),   ///< DMAMSPI19
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI20          = (124),   ///< DMAMSPI20
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI21          = (125),   ///< DMAMSPI21
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI22          = (126),   ///< DMAMSPI22
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI23          = (127),   ///< DMAMSPI23
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI24          = (128),   ///< DMAMSPI24
    DMAC_TRIGGER_EVENT_MSPI_DMAMSPI25          = (129),   ///< DMAMSPI25
    DMAC_TRIGGER_EVENT_PSI5_INTPSI50RI         = (130),   ///< INTPSI50RI
    DMAC_TRIGGER_EVENT_PSI5_INTPSI51RI         = (131),   ///< INTPSI51RI
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS00        = (132),   ///< INTGTM0DOS00
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS01        = (133),   ///< INTGTM0DOS01
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS02        = (134),   ///< INTGTM0DOS02
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS03        = (135),   ///< INTGTM0DOS03
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS04        = (136),   ///< INTGTM0DOS04
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS05        = (137),   ///< INTGTM0DOS05
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS06        = (138),   ///< INTGTM0DOS06
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS07        = (139),   ///< INTGTM0DOS07
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS10        = (140),   ///< INTGTM0DOS10
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS11        = (141),   ///< INTGTM0DOS11
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS12        = (142),   ///< INTGTM0DOS12
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS13        = (143),   ///< INTGTM0DOS13
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS14        = (144),   ///< INTGTM0DOS14
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS15        = (145),   ///< INTGTM0DOS15
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS16        = (146),   ///< INTGTM0DOS16
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS17        = (147),   ///< INTGTM0DOS17
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOSO0        = (148),   ///< INTGTM0DOSO0
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOSO1        = (149),   ///< INTGTM0DOSO1
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOSO2        = (150),   ///< INTGTM0DOSO2
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOSO3        = (151),   ///< INTGTM0DOSO3
    DMAC_TRIGGER_EVENT_SSIF_INTSSIF0TX         = (152),   ///< INTSSIF0TX
    DMAC_TRIGGER_EVENT_SSIF_INTSSIF0RX         = (153),   ///< INTSSIF0RX
    DMAC_TRIGGER_EVENT_SSIF_INTSSIF1TX         = (154),   ///< INTSSIF1TX
    DMAC_TRIGGER_EVENT_SSIF_INTSSIF1RX         = (155),   ///< INTSSIF1RX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C0IBI        = (156),   ///< INTRI3C0IBI
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C0RX0        = (157),   ///< INTRI3C0RX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C0TX0        = (158),   ///< INTRI3C0TX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C0HRX        = (159),   ///< INTRI3C0HRX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C0HTX        = (160),   ///< INTRI3C0HTX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C1IBI        = (161),   ///< INTRI3C1IBI
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C1RX0        = (162),   ///< INTRI3C1RX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C1TX0        = (163),   ///< INTRI3C1TX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C1HRX        = (164),   ///< INTRI3C1HRX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C1HTX        = (165),   ///< INTRI3C1HTX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C2IBI        = (166),   ///< INTRI3C2IBI
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C2RX0        = (167),   ///< INTRI3C2RX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C2TX0        = (168),   ///< INTRI3C2TX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C2HRX        = (169),   ///< INTRI3C2HRX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C2HTX        = (170),   ///< INTRI3C2HTX
    DMAC_TRIGGER_EVENT_FLASH_INTDMAFL0         = (171),   ///< INTDMAFL0
    DMAC_TRIGGER_EVENT_FLASH_INTDMAFL2         = (172),   ///< INTDMAFL2
    DMAC_TRIGGER_EVENT_OSTM_INTOSTM0TINT       = (173),   ///< INTOSTM0TINT
    DMAC_TRIGGER_EVENT_OSTM_INTOSTM1TINT       = (174),   ///< INTOSTM1TINT
    DMAC_TRIGGER_EVENT_TAPA_INTTAPA0IPEK0      = (176),   ///< INTTAPA0IPEK0
    DMAC_TRIGGER_EVENT_TAPA_INTTAPA0IVLY0      = (177),   ///< INTTAPA0IVLY0
    DMAC_TRIGGER_EVENT_TSG3_INTTSG30I11        = (178),   ///< INTTSG30I11
    DMAC_TRIGGER_EVENT_TSG3_INTTSG30I12        = (179),   ///< INTTSG30I12
    DMAC_TRIGGER_EVENT_TSG3_INTTSG30IPEK       = (180),   ///< INTTSG30IPEK
    DMAC_TRIGGER_EVENT_TSG3_INTTSG30IVLY       = (181),   ///< INTTSG30IVLY
    DMAC_TRIGGER_EVENT_TSG3_INTTSG31I11        = (182),   ///< INTTSG31I11
    DMAC_TRIGGER_EVENT_TSG3_INTTSG31I12        = (183),   ///< INTTSG31I12
    DMAC_TRIGGER_EVENT_TSG3_INTTSG31IPEK       = (184),   ///< INTTSG31IPEK
    DMAC_TRIGGER_EVENT_TSG3_INTTSG31IVLY       = (185),   ///< INTTSG31IVLY
    DMAC_TRIGGER_EVENT_ENCA_INTENCA0IOV        = (186),   ///< INTENCA0IOV
    DMAC_TRIGGER_EVENT_ENCA_INTENCA0I0         = (187),   ///< INTENCA0I0
    DMAC_TRIGGER_EVENT_ENCA_INTENCA0I1         = (188),   ///< INTENCA0I1
    DMAC_TRIGGER_EVENT_ENCA_INTENCA0IUD        = (189),   ///< INTENCA0IUD
    DMAC_TRIGGER_EVENT_ENCA_INTENCA0IEC        = (190),   ///< INTENCA0IEC
    DMAC_TRIGGER_EVENT_MMCA_DMAMMCA0           = (191),   ///< DMAMMCA0
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I0         = (192),   ///< INTTAUD0I0
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I1         = (193),   ///< INTTAUD0I1
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I2         = (194),   ///< INTTAUD0I2
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I3         = (195),   ///< INTTAUD0I3
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I4         = (196),   ///< INTTAUD0I4
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I5         = (197),   ///< INTTAUD0I5
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I6         = (198),   ///< INTTAUD0I6
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I7         = (199),   ///< INTTAUD0I7
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I8         = (200),   ///< INTTAUD0I8
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I9         = (201),   ///< INTTAUD0I9
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I10        = (202),   ///< INTTAUD0I10
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I11        = (203),   ///< INTTAUD0I11
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I12        = (204),   ///< INTTAUD0I12
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I13        = (205),   ///< INTTAUD0I13
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I14        = (206),   ///< INTTAUD0I14
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD0I15        = (207),   ///< INTTAUD0I15
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I0         = (208),   ///< INTTAUD1I0
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I1         = (209),   ///< INTTAUD1I1
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I2         = (210),   ///< INTTAUD1I2
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I3         = (211),   ///< INTTAUD1I3
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I4         = (212),   ///< INTTAUD1I4
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I5         = (213),   ///< INTTAUD1I5
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I6         = (214),   ///< INTTAUD1I6
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I7         = (215),   ///< INTTAUD1I7
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I8         = (216),   ///< INTTAUD1I8
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I9         = (217),   ///< INTTAUD1I9
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I10        = (218),   ///< INTTAUD1I10
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I11        = (219),   ///< INTTAUD1I11
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I12        = (220),   ///< INTTAUD1I12
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I13        = (221),   ///< INTTAUD1I13
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I14        = (222),   ///< INTTAUD1I14
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD1I15        = (223),   ///< INTTAUD1I15
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I0         = (224),   ///< INTTAUD2I0
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I1         = (225),   ///< INTTAUD2I1
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I2         = (226),   ///< INTTAUD2I2
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I3         = (227),   ///< INTTAUD2I3
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I4         = (228),   ///< INTTAUD2I4
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I5         = (229),   ///< INTTAUD2I5
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I6         = (230),   ///< INTTAUD2I6
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I7         = (231),   ///< INTTAUD2I7
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I8         = (232),   ///< INTTAUD2I8
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I9         = (233),   ///< INTTAUD2I9
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I10        = (234),   ///< INTTAUD2I10
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I11        = (235),   ///< INTTAUD2I11
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I12        = (236),   ///< INTTAUD2I12
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I13        = (237),   ///< INTTAUD2I13
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I14        = (238),   ///< INTTAUD2I14
    DMAC_TRIGGER_EVENT_TAUD_INTTAUD2I15        = (239),   ///< INTTAUD2I15
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ0I0         = (240),   ///< INTTAUJ0I0
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ0I1         = (241),   ///< INTTAUJ0I1
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ0I2         = (242),   ///< INTTAUJ0I2
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ0I3         = (243),   ///< INTTAUJ0I3
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ1I0         = (244),   ///< INTTAUJ1I0
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ1I1         = (245),   ///< INTTAUJ1I1
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ1I2         = (246),   ///< INTTAUJ1I2
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ1I3         = (247),   ///< INTTAUJ1I3
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ2I0         = (248),   ///< INTTAUJ2I0
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ2I1         = (249),   ///< INTTAUJ2I1
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ2I2         = (250),   ///< INTTAUJ2I2
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ2I3         = (251),   ///< INTTAUJ2I3
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ3I0         = (252),   ///< INTTAUJ3I0
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ3I1         = (253),   ///< INTTAUJ3I1
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ3I2         = (254),   ///< INTTAUJ3I2
    DMAC_TRIGGER_EVENT_TAUJ_INTTAUJ3I3         = (255),   ///< INTTAUJ3I3
    DMAC_TRIGGER_EVENT_ADCK_INTADCK2I0         = (256),   ///< INTADCK2I0
    DMAC_TRIGGER_EVENT_ADCK_INTADCK2I1         = (257),   ///< INTADCK2I1
    DMAC_TRIGGER_EVENT_ADCK_INTADCK2I2         = (258),   ///< INTADCK2I2
    DMAC_TRIGGER_EVENT_ADCK_INTADCK2I3         = (259),   ///< INTADCK2I3
    DMAC_TRIGGER_EVENT_ADCK_INTADCK2I4         = (260),   ///< INTADCK2I4
    DMAC_TRIGGER_EVENT_ADCK_ADMPXI2            = (261),   ///< ADMPXI2
    DMAC_TRIGGER_EVENT_ADCK_ADC_CONV_END2      = (262),   ///< ADC_CONV_END2
    DMAC_TRIGGER_EVENT_ADCK_INTADCK_SD2        = (263),   ///< INTADCK_SD2
    DMAC_TRIGGER_EVENT_PORT_IRQ32              = (290),   ///< IRQ32
    DMAC_TRIGGER_EVENT_PORT_IRQ33              = (291),   ///< IRQ33
    DMAC_TRIGGER_EVENT_PORT_IRQ34              = (292),   ///< IRQ34
    DMAC_TRIGGER_EVENT_PORT_IRQ35              = (293),   ///< IRQ35
    DMAC_TRIGGER_EVENT_PORT_IRQ36              = (294),   ///< IRQ36
    DMAC_TRIGGER_EVENT_PORT_IRQ37              = (295),   ///< IRQ37
    DMAC_TRIGGER_EVENT_PORT_IRQ38              = (296),   ///< IRQ38
    DMAC_TRIGGER_EVENT_PORT_IRQ39              = (297),   ///< IRQ39
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ6  = (328),   ///< INTRCANCFDREQ6
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ7  = (329),   ///< INTRCANCFDREQ7
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ8  = (330),   ///< INTRCANCFDREQ8
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ9  = (331),   ///< INTRCANCFDREQ9
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ10 = (332),   ///< INTRCANCFDREQ10
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ11 = (333),   ///< INTRCANCFDREQ11
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ12 = (334),   ///< INTRCANCFDREQ12
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANCFDREQ13 = (335),   ///< INTRCANCFDREQ13
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ8  = (338),   ///< INTRCANRFDREQ8
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ9  = (339),   ///< INTRCANRFDREQ9
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ10 = (340),   ///< INTRCANRFDREQ10
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ11 = (341),   ///< INTRCANRFDREQ11
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ12 = (342),   ///< INTRCANRFDREQ12
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ13 = (343),   ///< INTRCANRFDREQ13
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ14 = (344),   ///< INTRCANRFDREQ14
    DMAC_TRIGGER_EVENT_RSCANFD_INTRCANRFDREQ15 = (345),   ///< INTRCANRFDREQ15
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH0 = (346),   ///< INTPSI5S0RXDMACH0
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH1 = (347),   ///< INTPSI5S0RXDMACH1
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH2 = (348),   ///< INTPSI5S0RXDMACH2
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH3 = (349),   ///< INTPSI5S0RXDMACH3
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH4 = (350),   ///< INTPSI5S0RXDMACH4
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH5 = (351),   ///< INTPSI5S0RXDMACH5
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH6 = (352),   ///< INTPSI5S0RXDMACH6
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0RXDMACH7 = (353),   ///< INTPSI5S0RXDMACH7
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH1 = (354),   ///< INTPSI5S0TXDMACH1
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH2 = (355),   ///< INTPSI5S0TXDMACH2
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH3 = (356),   ///< INTPSI5S0TXDMACH3
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH4 = (357),   ///< INTPSI5S0TXDMACH4
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH5 = (358),   ///< INTPSI5S0TXDMACH5
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH6 = (359),   ///< INTPSI5S0TXDMACH6
    DMAC_TRIGGER_EVENT_PSI5S_INTPSI5S0TXDMACH7 = (360),   ///< INTPSI5S0TXDMACH7
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN315UR0     = (361),   ///< INTRLIN315UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN315UR1     = (362),   ///< INTRLIN315UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN316UR0     = (363),   ///< INTRLIN316UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN316UR1     = (364),   ///< INTRLIN316UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN317UR0     = (365),   ///< INTRLIN317UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN317UR1     = (366),   ///< INTRLIN317UR1
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN318UR0     = (367),   ///< INTRLIN318UR0
    DMAC_TRIGGER_EVENT_RLIN3_INTRLIN318UR1     = (368),   ///< INTRLIN318UR1
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS20        = (408),   ///< INTGTM0DOS20
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS21        = (409),   ///< INTGTM0DOS21
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS22        = (410),   ///< INTGTM0DOS22
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS23        = (411),   ///< INTGTM0DOS23
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS24        = (412),   ///< INTGTM0DOS24
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS25        = (413),   ///< INTGTM0DOS25
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS26        = (414),   ///< INTGTM0DOS26
    DMAC_TRIGGER_EVENT_GTM_INTGTM0DOS27        = (415),   ///< INTGTM0DOS27
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C3IBI        = (427),   ///< INTRI3C3IBI
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C3RX0        = (428),   ///< INTRI3C3RX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C3TX0        = (429),   ///< INTRI3C3TX0
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C3HRX        = (430),   ///< INTRI3C3HRX
    DMAC_TRIGGER_EVENT_RI3C_INTRI3C3HTX        = (431),   ///< INTRI3C3HTX
    DMAC_TRIGGER_EVENT_SOFTWARE                = (1024U), ///< SOFTWARE TRIGGER
} dmac_trigger_event_t;

/***********************************************************************************************************************
 * Exported global variables (to be accessed by other files)
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Private global variables and functions
 **********************************************************************************************************************/

#endif                                 /* BSP_DMAC_H */

/** @} (end addtogroup BSP_MCU_RH850U2C8) */
