/*
* Copyright (c) 2025 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/* Ensure Renesas MCU variation definitions are included to ensure MCU
 * specific register variations are handled correctly. */
#ifndef BSP_FEATURE_H
 #error "INTERNAL ERROR: bsp_cfg.h must be included before renesas.h."
#endif

/** @addtogroup Renesas
 * @{
 */

/** @addtogroup RH850
 * @{
 */

#ifndef RENESAS_H
 #define RENESAS_H

 #ifdef __cplusplus
extern "C" {
 #endif

/** @addtogroup Configuration_of_RH850
 * @{
 */

/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */
/* IRQn_Type is provided in bsp_exceptions.h. Vectors generated by the FSP Configuration tool are in vector_data.h */

/** @} */ /* End of group Configuration_of_RH850 */

/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

 #if (BSP_MCU_GROUP_RH850U2Bx)
  #include "r7f70255x.h"
 #elif (BSP_MCU_GROUP_RH850U2Ax)
  #include "r7f70230x.h"
 #elif (BSP_MCU_GROUP_RH850U2BxE)
  #include "r7f70259x.h"
 #elif (BSP_MCU_GROUP_RH850U2Cx)
  #include "r7f70260x.h"
 #else
  #warning "Unsupported MCU"
 #endif

 #ifdef __cplusplus
}
 #endif

#endif                                 /* RENESAS_H */

/** @} */ /* End of group RH850 */

/** @} */ /* End of group Renesas */
